# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/ecs.hsc.philips.com.cn_instances.yaml
# +kubebuilder:scaffold:crdkustomizeresource
